// Package docs renders the registry as Markdown.
//
// The reference is generated rather than written so it cannot describe a tool the server does
// not have, or miss one it does. Because the rendering includes each tool's generated JSON
// Schema, the committed file is also the schema snapshot: changing a field's name, type or
// description shows up as a diff in review rather than as a silent contract change.
package docs

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/google/jsonschema-go/jsonschema"
	"github.com/wowsims/tbc/mcp/internal/spec"
)

// Path is where the rendered reference lives, relative to the module root.
const Path = "docs/TOOLS.md"

const header = `<!--
Generated by "make mcp-docs" from the declarations in mcp/internal/{tools,resources,prompts}.
Do not edit: your changes will be overwritten, and the committed schemas below are what the
snapshot test compares against.
-->

# wowsims-tbc MCP reference

Every tool is a function of its arguments. The server keeps nothing between calls: simulations
are addressed by a content hash of the request, so the same arguments always name the same run,
and any instance can answer for any ID.
`

// Render returns the full Markdown reference for the given entries.
func Render(entries []spec.Entry) (string, error) {
	documents, err := spec.Docs(entries)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString(header)

	for _, section := range []struct {
		kind  spec.Kind
		title string
		empty string
	}{
		{spec.KindTool, "Tools", "No tools yet."},
		{spec.KindResource, "Resources", "No resources yet."},
		{spec.KindPrompt, "Prompts", "No prompts yet."},
	} {
		b.WriteString("\n## ")
		b.WriteString(section.title)
		b.WriteString("\n")

		var rendered int
		for _, doc := range documents {
			if doc.Kind != section.kind {
				continue
			}
			rendered++
			if err := renderEntry(&b, doc); err != nil {
				return "", err
			}
		}

		if rendered == 0 {
			b.WriteString("\n")
			b.WriteString(section.empty)
			b.WriteString("\n")
		}
	}

	return b.String(), nil
}

func renderEntry(b *strings.Builder, doc spec.Doc) error {
	b.WriteString("\n### `")
	b.WriteString(doc.ID)
	b.WriteString("`")
	if doc.Title != "" {
		b.WriteString(" — ")
		b.WriteString(doc.Title)
	}
	b.WriteString("\n\n")
	b.WriteString(doc.Description)
	b.WriteString("\n")

	if doc.MIMEType != "" {
		fmt.Fprintf(b, "\nReturns `%s`.\n", doc.MIMEType)
	}

	if doc.Annotations != nil && doc.Annotations.ReadOnlyHint {
		b.WriteString("\nRead-only.\n")
	}

	if len(doc.Arguments) > 0 {
		b.WriteString("\n| Argument | Required | Description |\n| --- | --- | --- |\n")
		for _, argument := range doc.Arguments {
			required := "no"
			if argument.Required {
				required = "yes"
			}
			fmt.Fprintf(b, "| `%s` | %s | %s |\n", argument.Name, required, argument.Description)
		}
	}

	if doc.Text != "" {
		b.WriteString("\n<details><summary>Workflow</summary>\n\n```\n")
		b.WriteString(doc.Text)
		b.WriteString("\n```\n\n</details>\n")
	}

	if err := renderSchema(b, "Input", doc.InputSchema); err != nil {
		return fmt.Errorf("%s: %w", doc.ID, err)
	}
	if err := renderSchema(b, "Output", doc.OutputSchema); err != nil {
		return fmt.Errorf("%s: %w", doc.ID, err)
	}
	return nil
}

func renderSchema(b *strings.Builder, label string, schema *jsonschema.Schema) error {
	if schema == nil {
		return nil
	}

	encoded, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return err
	}

	b.WriteString("\n<details><summary>")
	b.WriteString(label)
	b.WriteString(" schema</summary>\n\n```json\n")
	b.Write(encoded)
	b.WriteString("\n```\n\n</details>\n")
	return nil
}
